shell check:
  image: koalaman/shellcheck-alpine:stable
  stage: test
  before_script:
    - shellcheck --version
  script:
    - shellcheck scr/**/*.sh

shfmt:
  image: mvdan/shfmt:v3.1.0-alpine
  stage: test
  before_script:
    - shfmt -version
  script:
    - shfmt -ln posix -i 2 -ci -d scr/**/*.sh # path to your shell scripts

.prepare:
  image: ubuntu:focal
  stage: build
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -qq -y install qemu qemu-user-static binfmt-support arch-install-scripts linux-image-generic libguestfs-tools wget p7zip-full xz-utils
    - chmod +x src/*.sh
    - mkdir -p /root/linux/

arch:
  extends: .prepare
  script:
    - HEKATE=true DISTRO=ARCH ./src/entrypoint.sh /root/linux/
  artifacts:
    paths:
      - /root/linux/SWR-Arch.img

arch_hekate:
  extends: .prepare
  script:
    - HEKATE=true DISTRO=ARCH ./src/entrypoint.sh /root/linux/
  artifacts:
    paths:
      - /root/linux/SWR-Arch.7z

fedora:
  extends: .prepare
  script:
    - HEKATE=true DISTRO=FEDORA ./src/entrypoint.sh /root/linux/
  artifacts:
    paths:
      - /root/linux/SWR-Fedora.img

fedora_hekate:
  extends: .prepare
  script:
    - HEKATE=true DISTRO=FEDORA ./src/entrypoint.sh /root/linux/
  artifacts:
    paths:
      - /root/linux/SWR-Fedora.7z
