image: ubuntu:focal

.prepare:
  stage: build
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -qq -y install qemu qemu-user-static binfmt-support arch-install-scripts linux-image-generic libguestfs-tools wget p7zip-full xz-utils
    - chmod +x src/*.sh
    - mkdir -p linux/

arch:
  extends: .prepare
  script:
    - HEKATE=true DISTRO=ARCH ./src/entrypoint.sh linux/
  artifacts:
    paths:
      - linux/SWR-Arch.img

arch_hekate:
  extends: .prepare
  script:
    - HEKATE=true DISTRO=ARCH ./src/entrypoint.sh linux/
  artifacts:
    paths:
      - linux/SWR-Arch.7z

fedora:
  extends: .prepare
  script:
    - HEKATE=true DISTRO=FEDORA ./src/entrypoint.sh linux/
  artifacts:
    paths:
      - linux/SWR-Fedora.img

fedora_hekate:
  extends: .prepare
  script:
    - HEKATE=true DISTRO=FEDORA ./src/entrypoint.sh linux/
  artifacts:
    paths:
      - linux/SWR-Fedora.7z
